import { DIMENSION_KEYS, dimensionLabel } from "@/lib/features/dimensions";
import { correlation, mean, round } from "@/lib/utils/math";
import { centeredFeatures } from "./catalog";
import { computeMetrics } from "./metrics";
import type { HarnessPolicy } from "./policy-schema";
import { effectiveStrength } from "./preference-state";
import type { ReplayDataset, ReplayRow } from "./replay";
import { PREDICTIVE_COMPONENTS, type PredictiveComponent } from "./types";

export const FAILURE_CATEGORIES = [
  "miscalibrated_threshold",
  "overweighted_component",
  "underweighted_component",
  "ignored_negative_preference",
  "recent_preference_shift",
  "stale_long_term_memory",
  "overfit_single_dimension",
  "underweighted_dimension",
  "too_little_exploration",
  "excessive_exploration",
] as const;
export type FailureCategory = (typeof FAILURE_CATEGORIES)[number];

export interface FailureFinding {
  category: FailureCategory;
  /** 0..1, how strongly the evidence points at this failure. */
  severity: number;
  summary: string;
  /** Quantitative evidence computed from replay — never generated by an LLM. */
  evidence: Record<string, number | string>;
  component?: PredictiveComponent;
  dimension?: string;
  direction?: "increase" | "decrease";
}

export interface FailureReport {
  n: number;
  errors: number;
  falsePositives: number;
  falseNegatives: number;
  findings: FailureFinding[];
  componentCorrelation: Record<PredictiveComponent, number>;
  componentWeightShare: Record<PredictiveComponent, number>;
}

const COMPONENT_LABEL: Record<PredictiveComponent, string> = {
  semantic: "semantic similarity",
  explicit: "explicit onboarding preferences",
  inferred: "learned lifestyle/amenity preferences",
  visual: "learned visual preferences",
  behavior: "similarity to engaged homes",
  metadata: "listing metadata (price/bedroom sweet spot)",
};

function pct(value: number): string {
  return `${Math.round(value * 100)}%`;
}

/**
 * Turns replay results into quantitative failure findings. Every number here comes from the
 * replayed predictions; an optional LLM may only narrate these findings afterward.
 */
export function analyzeFailures(rows: ReplayRow[], dataset: ReplayDataset, policy: HarnessPolicy): FailureReport {
  const metrics = computeMetrics(rows);
  const labels = rows.map((r) => (r.actual === "LIKE" ? 1 : 0));
  const findings: FailureFinding[] = [];
  const fps = rows.filter((r) => r.predicted === "LIKE" && r.actual === "DISLIKE");
  const fns = rows.filter((r) => r.predicted === "DISLIKE" && r.actual === "LIKE");

  // 1. Threshold calibration: predicted-positive rate vs. actual like rate.
  const gap = metrics.predictedPositiveRate - metrics.likeRate;
  if (Math.abs(gap) >= 0.12) {
    findings.push({
      category: "miscalibrated_threshold",
      severity: Math.min(1, Math.abs(gap) * 2),
      summary:
        gap > 0
          ? `Predicts LIKE for ${pct(metrics.predictedPositiveRate)} of homes but the user liked only ${pct(metrics.likeRate)} — the like threshold is too permissive.`
          : `Predicts LIKE for only ${pct(metrics.predictedPositiveRate)} of homes while the user liked ${pct(metrics.likeRate)} — the like threshold is too strict.`,
      evidence: { predictedPositiveRate: round(metrics.predictedPositiveRate), likeRate: round(metrics.likeRate) },
      direction: gap > 0 ? "increase" : "decrease",
    });
  }

  // 2. Component usefulness: correlation with outcome vs. share of the fit weight.
  const predictiveSum = PREDICTIVE_COMPONENTS.reduce((s, c) => s + policy.rankingWeights[c], 0) || 1;
  const componentCorrelation = {} as Record<PredictiveComponent, number>;
  const componentWeightShare = {} as Record<PredictiveComponent, number>;
  for (const c of PREDICTIVE_COMPONENTS) {
    componentCorrelation[c] = round(correlation(rows.map((r) => r.breakdown[c]), labels));
    componentWeightShare[c] = round(policy.rankingWeights[c] / predictiveSum);
  }
  const maxCorr = Math.max(...PREDICTIVE_COMPONENTS.map((c) => componentCorrelation[c]));
  for (const c of PREDICTIVE_COMPONENTS) {
    const corr = componentCorrelation[c];
    const share = componentWeightShare[c];
    if (share >= 0.15 && corr < 0.1 && maxCorr - corr > 0.15) {
      findings.push({
        category: "overweighted_component",
        component: c,
        direction: "decrease",
        severity: Math.min(1, share * 1.5 + (maxCorr - corr)),
        summary: `${COMPONENT_LABEL[c]} carries ${pct(share)} of the prediction weight but barely tracks outcomes (r=${corr.toFixed(2)}).`,
        evidence: { correlation: corr, weightShare: share, bestCorrelation: round(maxCorr) },
      });
    } else if (corr >= 0.2 && share < 0.25 && corr >= maxCorr - 0.1) {
      findings.push({
        category: "underweighted_component",
        component: c,
        direction: "increase",
        severity: Math.min(1, corr + (0.25 - share)),
        summary: `${COMPONENT_LABEL[c]} is among the strongest predictors of likes (r=${corr.toFixed(2)}) but has only ${pct(share)} of the weight.`,
        evidence: { correlation: corr, weightShare: share },
      });
    }
  }

  // 3. Ignored negatives: false positives on homes with a feature the user has shown they dislike.
  const negativeHitCounts = new Map<string, number>();
  let fpWithNegative = 0;
  for (const r of fps) {
    const p = dataset.properties.get(r.example.propertyId);
    if (!p) continue;
    let hit = false;
    for (const key of DIMENSION_KEYS) {
      const dim = r.state.dimensions[key];
      if (!dim) continue;
      const strength = effectiveStrength(dim, policy.memoryPolicy);
      if (strength <= -0.15 && (p.features[key] ?? 0) >= 0.6) {
        hit = true;
        negativeHitCounts.set(key, (negativeHitCounts.get(key) ?? 0) + 1);
      }
    }
    if (hit) fpWithNegative++;
  }
  if (fps.length >= 2 && fpWithNegative / fps.length >= 0.35) {
    const top = [...negativeHitCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 3);
    findings.push({
      category: "ignored_negative_preference",
      direction: "increase",
      severity: Math.min(1, fpWithNegative / fps.length),
      summary: `${fpWithNegative} of ${fps.length} false positives had a feature the user already rejects (${top.map(([k]) => dimensionLabel(k).toLowerCase()).join(", ")}).`,
      evidence: {
        falsePositives: fps.length,
        withKnownNegative: fpWithNegative,
        topNegatives: top.map(([k, v]) => `${k}:${v}`).join(","),
      },
    });
  }

  // 4. Recent vs. long-term memory: which view of the user predicts the latest behavior better?
  const lateRows = rows.slice(Math.floor(rows.length / 2));
  const lateLabels = lateRows.map((r) => (r.actual === "LIKE" ? 1 : 0));
  const recentCorr = correlation(lateRows.map((r) => r.recentOnlyFit ?? 0.5), lateLabels);
  const longCorr = correlation(lateRows.map((r) => r.longTermOnlyFit ?? 0.5), lateLabels);
  const earlyErr = 1 - computeMetrics(rows.slice(0, Math.floor(rows.length / 2))).accuracy;
  const lateErr = 1 - computeMetrics(lateRows).accuracy;
  if (lateRows.length >= 6 && recentCorr - longCorr >= 0.08) {
    findings.push({
      category: "recent_preference_shift",
      direction: "increase",
      severity: Math.min(1, (recentCorr - longCorr) * 3),
      summary: `Recent behavior predicts the latest outcomes better than long-term memory (r=${recentCorr.toFixed(2)} vs ${longCorr.toFixed(2)}); preferences appear to be shifting.`,
      evidence: {
        recentOnlyCorrelation: round(recentCorr),
        longTermOnlyCorrelation: round(longCorr),
        earlyErrorRate: round(earlyErr),
        lateErrorRate: round(lateErr),
      },
    });
  } else if (lateRows.length >= 6 && longCorr - recentCorr >= 0.08 && policy.memoryPolicy.recentMemoryWeight > policy.memoryPolicy.longTermMemoryWeight) {
    findings.push({
      category: "stale_long_term_memory",
      direction: "increase",
      severity: Math.min(1, (longCorr - recentCorr) * 3),
      summary: `Long-term memory predicts better than the recent window (r=${longCorr.toFixed(2)} vs ${recentCorr.toFixed(2)}); recent behavior is noisy and over-weighted.`,
      evidence: { recentOnlyCorrelation: round(recentCorr), longTermOnlyCorrelation: round(longCorr) },
    });
  }

  // 5. Per-dimension signal vs. how much the model uses it.
  const dimStats = DIMENSION_KEYS.map((key, i) => {
    const values = rows.map((r) => {
      const p = dataset.properties.get(r.example.propertyId);
      return p ? centeredFeatures(p, dataset.stats)[i] : 0;
    });
    const corr = correlation(values, labels);
    const usage = mean(rows.map((r) => Math.abs(r.weights[i])));
    return { key, corr, usage };
  });
  const totalUsage = dimStats.reduce((s, d) => s + d.usage, 0) || 1;
  const dominant = [...dimStats].sort((a, b) => b.usage - a.usage)[0];
  if (dominant && dominant.usage / totalUsage > 0.3 && Math.abs(dominant.corr) < 0.15) {
    findings.push({
      category: "overfit_single_dimension",
      dimension: dominant.key,
      direction: "decrease",
      severity: Math.min(1, dominant.usage / totalUsage),
      summary: `${dimensionLabel(dominant.key)} drives ${pct(dominant.usage / totalUsage)} of learned weight yet barely separates likes from dislikes (r=${dominant.corr.toFixed(2)}).`,
      evidence: { usageShare: round(dominant.usage / totalUsage), correlation: round(dominant.corr) },
    });
  }
  const usageRank = [...dimStats].sort((a, b) => b.usage - a.usage).map((d) => d.key);
  for (const d of [...dimStats].sort((a, b) => Math.abs(b.corr) - Math.abs(a.corr)).slice(0, 3)) {
    if (Math.abs(d.corr) >= 0.25 && usageRank.indexOf(d.key) >= 8) {
      findings.push({
        category: "underweighted_dimension",
        dimension: d.key,
        direction: "increase",
        severity: Math.min(1, Math.abs(d.corr)),
        summary: `${dimensionLabel(d.key)} strongly separates likes from dislikes (r=${d.corr.toFixed(2)}) but ranks #${usageRank.indexOf(d.key) + 1} in learned weight.`,
        evidence: { correlation: round(d.corr), usageRank: usageRank.indexOf(d.key) + 1 },
      });
    }
  }

  // 6. Exploration balance.
  const latest = rows[rows.length - 1]?.state;
  const uncertain = latest
    ? DIMENSION_KEYS.filter((k) => (latest.dimensions[k]?.confidence ?? 0) < policy.explorationPolicy.minConfidenceTarget && (dataset.stats.featureStd[DIMENSION_KEYS.indexOf(k)] ?? 0) >= 0.15)
    : [];
  if (uncertain.length >= 6 && (policy.explorationPolicy.rate < 0.1 || policy.explorationPolicy.strategy !== "uncertainty")) {
    findings.push({
      category: "too_little_exploration",
      direction: "increase",
      severity: Math.min(1, uncertain.length / 15),
      summary: `${uncertain.length} informative dimensions are still low-confidence while exploration is ${pct(policy.explorationPolicy.rate)} (${policy.explorationPolicy.strategy}).`,
      evidence: { uncertainDimensions: uncertain.length, explorationRate: policy.explorationPolicy.rate, examples: uncertain.slice(0, 4).join(",") },
    });
  }
  if (metrics.explorationCount >= 5 && metrics.explorationLikeRate < metrics.likeRate * 0.4 && policy.explorationPolicy.rate > 0.15) {
    findings.push({
      category: "excessive_exploration",
      direction: "decrease",
      severity: 0.6,
      summary: `Exploration homes are liked ${pct(metrics.explorationLikeRate)} of the time vs ${pct(metrics.likeRate)} overall; exploration is costing too much.`,
      evidence: { explorationLikeRate: round(metrics.explorationLikeRate), likeRate: round(metrics.likeRate) },
    });
  }

  findings.sort((a, b) => b.severity - a.severity);
  return {
    n: rows.length,
    errors: fps.length + fns.length,
    falsePositives: fps.length,
    falseNegatives: fns.length,
    findings,
    componentCorrelation,
    componentWeightShare,
  };
}
